# Thanks for downloading ViaVersion
# Ensure you look through all these options
# If you need help:
# Discord - https://viaversion.com/discord
# Docs - https://docs.viaversion.com
#
#----------------------------------------------------------#
#                     GLOBAL OPTIONS                       #
#----------------------------------------------------------#
#
# Should ViaVersion check for updates?
check-for-updates: false
# Send the supported versions with the Status (Ping) response packet
send-supported-versions: true
# Easier to configure alternative to 'block-protocols'. Uses readable version strings with possible '<' and '>' prefixes.
# An example to block 1.16.4, everything below 1.16, as well as everything above 1.17.1 would be: ["<1.16", "1.16.4", ">1.17.1"]
# You can use both this and the block-protocols option at the same time as well.
block-versions: []
# Block specific Minecraft protocol version numbers.
# List of all Minecraft protocol versions: https://minecraft.wiki/w/Protocol_version, or use a generator: https://via.krusic22.com
block-protocols: []
# Change the blocked disconnect message
block-disconnect-msg: |
  §7[§aTrue§cOG§7] §eNetwork §cUnsupported client! §c:(
    §4♥ §6Please re-log using MCJE 1.8-1.21.11 §4♥
reload-disconnect-msg: |
  §7[§aTrue§cOG§7] §eNetwork §6Server is restarting... §4♥
logging:
  log-blocked-joins: false
  log-entity-data-errors: true
  log-text-component-conversion-errors: true
  log-other-conversion-warnings: false
  max-error-length: 1500
config-version: 1
init-config-version: 1
migrate-default-config-changes: false
send-player-details: true
send-server-details: true
packet-limiter:
  enabled: true
  max-per-second: 800
  max-per-second-kick-message: Your client is sending too many packets.
  sustained-max-per-second: 200
  sustained-period-seconds: 7
  sustained-threshold: 4
  sustained-kick-message: Your client is sending way too many packets!
packet-size-limiter:
  enabled: true
  max-per-second: -1
  max-per-second-kick-message: Your client is sending too many packets per second.
  sustained-max-per-second: -1
  sustained-period-seconds: 5
  sustained-threshold: 3
  sustained-kick-message: Your client is sending packets which are larger than the limit!
hologram-patch: true
hologram-y: -0.96
register-userconnections-on-join: true
piston-animation-patch: true
quick-move-action-fix: true
team-colour-fix: true
disable-1_13-auto-complete: false
1_13-tab-complete-delay: 2
fix-low-snow-collision: true
fix-infested-block-breaking: false
truncate-1_14-books: false
change-1_9-hitbox: true
change-1_14-hitbox: false
fix-non-full-blocklight: true
fix-1_14-health-nan: true
use-1_15-instant-respawn: false
serverside-blockconnections: true
blockconnection-method: packet
reduce-blockstorage-memory: false
flowerstem-when-block-above: true
vine-climb-fix: true
ignore-long-1_16-channel-names: true
forced-use-1_17-resource-pack: false
resource-pack-1_17-prompt: ''
cache-1_17-light: true
armor-toggle-fix: true
map-1_16-world-names:
  overworld: minecraft:overworld
  nether: minecraft:the_nether
  end: minecraft:the_end
translate-ocelot-to-cat: false
enforce-secure-chat: false
handle-invalid-item-count: false
hide-scoreboard-numbers: false
fix-1_21-placement-rotation: false
cancel-swing-in-inventory: true
prevent-collision: true
auto-team: true
shield-blocking: true
no-delay-shield-blocking: true
show-shield-when-sword-in-hand: false
simulate-pt: true
nms-player-ticking: true
bossbar-patch: true
bossbar-anti-flicker: false
use-new-effect-indicator: false
use-new-deathmessages: true
item-cache: true
replace-pistons: false
replacement-piston-id: 0
chunk-border-fix: false
left-handed-handling: true
cancel-block-sounds: true
use-1_8-hitbox-margin: true
